export const ROUTES = {
  HOME: '/',
  PRODUCT: `/products`,
  CHECKOUT: '/checkout',
  CONTACT: '/contact-us',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  FAQ: '/faq',
  FORGET_PASSWORD: '/forget-password',
  CHANGE_PASSWORD: '/my-account/change-password',
  ACCOUNT: '/my-account/account-settings',
  ACCOUNT_SETTING: '/my-account/account-settings',
  HELP_CENTER: '/my-account/help-center',
  NOTIFICATION: '/my-account/notification',
  SHOPS: '/shops',
  LOGIN: '/signin',
  SIGN_UP: '/signup',
  SEARCH: '/search',
  PRODUCTS: '/products',
  BUNDLE: '/bundles',
  CATEGORY: '/category',
  CART: '/my-account/cart',
  WISHLIST: '/my-account/wishlist',
};
